-- V4: Reset admin password to a verified bcrypt hash of 'admin123'
-- The hash generated by Spring Security BCryptPasswordEncoder (strength 10)
-- This replaces the V1 hash which may be invalid
UPDATE admins
SET password_hash = '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBpwTMRm5.yS.G'
WHERE username = 'admin';

-- Insert admin if not already present (idempotent)
INSERT INTO admins (username, password_hash)
SELECT 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBpwTMRm5.yS.G'
WHERE NOT EXISTS (SELECT 1 FROM admins WHERE username = 'admin');
